# Generated by Django 6.0.6 on 2026-06-08 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitemavailability',
            options={'verbose_name': 'Menu Item Availability', 'verbose_name_plural': 'Menu Item Availabilities'},
        ),
    ]
