# Generated by Django 6.0.6 on 2026-06-08 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_alter_menuitemavailability_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'Menu', 'verbose_name_plural': 'Menus'},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'verbose_name': 'Menu Item', 'verbose_name_plural': 'Menu Items'},
        ),
        migrations.AlterUniqueTogether(
            name='menuitemavailability',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='menuitemavailability',
            constraint=models.UniqueConstraint(fields=('menu_item', 'date'), name='unique_menu_item_date'),
        ),
    ]
