# Generated by Django 6.0.6 on 2026-06-13 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0003_alter_menu_options_alter_menuitem_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='active',
            new_name='is_active',
        ),
    ]
