# Generated by Django 6.0.6 on 2026-06-13 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0004_rename_active_menuitem_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
