# Generated by Django 6.0.6 on 2026-06-13 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0005_alter_menuitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.PositiveIntegerField(help_text='Price in Toman'),
        ),
    ]
