# Generated by Django 6.0.6 on 2026-06-30 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0007_menuitem_average_rating_menuitem_favorites_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='average_rating',
        ),
    ]
