# Generated by Django 6.0.6 on 2026-06-08 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cookprofile',
            options={'verbose_name': 'Cook Profile', 'verbose_name_plural': 'Cook Profiles'},
        ),
    ]
