# Generated by Django 6.0.6 on 2026-06-25 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooks', '0002_alter_cookprofile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookprofile',
            name='average_rating',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=3, null=True),
        ),
    ]
