# Generated by Django 6.0.6 on 2026-06-25 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooks', '0003_alter_cookprofile_average_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookprofile',
            name='reviews_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
