# Generated by Django 6.0.6 on 2026-06-27 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooks', '0004_cookprofile_reviews_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookprofile',
            name='favorites_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
