# Generated by Django 6.0.6 on 2026-06-18 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='is_approved',
            new_name='is_active',
        ),
    ]
